### ISSUE TITLE
Add a VCS reset command to the CLI

### ISSUE THREAD

**Issue by mrsimonemms** [konstructio/kubefirst#2245]
### What is your feature idea?

As a Kubefirst developer, one of the biggest frustrations is that I have to manually remove the GitHub/GitLab repos, teams etc before I can reinstall Kubefirst. This massively slows down my development.

An example using the GitHub command line tool:

```shell
function gh-clean(){
  gh api \
    --method DELETE \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    /orgs/${1}/teams/admins

  gh api \
    --method DELETE \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    /orgs/${1}/teams/developers

  gh repo delete ${1}/gitops --yes

  gh repo delete ${1}/metaphor --yes

}
```

### Why is it needed?

It would mean that we would have a complete deprovisioning strategy which we could link to in our docs.

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
Unless you discussed with @johndietz or @jarededwards about this feature, we don't want something like that. It make it too easy to destroy the `gitops` repository.

Since day one I asked for an easy way to destroy the clusters, but want the users to do it manually so we are not responsible for destroying things they wanted to keep (which the most important, is the git repositories). Hence why the deprovision process is not automated, and a step by step process so they can decide to delete or keep some things https://docs.kubefirst.io/civo/deprovision

It's also why I create my own script for my tests.
